name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build Debug
        run: dotnet build --no-restore --configuration Debug R4Utils
      - name: Build Release
        run: dotnet build --no-restore --configuration Release R4Utils
      - name: Test
        run: dotnet test --verbosity normal R4UtilsTester
      - name: Upload dotnet results
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: R4Utils/bin/Release/net5.0
        # Use always() to always run this step to publish results
        if: ${{ always() }}