name: Nuget push for development builds

on:
  push
  
jobs:
  publish-dev:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore R4Utils
      - name: Build Debug
        run: dotnet build -c Debug R4Utils
      - name: Create Name
        run: echo "SUFFIX=dev.$(tr /- .. <<<$GITHUB_REF).${GITHUB_RUN_ID}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --no-build --no-dependencies -p:PackageId=R4UtilsDev --version-suffix $SUFFIX
      - name: Push
        run: dotnet nuget push R4Utils/bin/Debug/R4UtilsDev.1.0.0-$SUFFIX.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
