name: Nuget push for pre-releases

on:
  push:
    branches: [ master ]

jobs:
  publish-pre:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore R4Utils
      - name: Build Release
        run: dotnet build -c Release R4Utils
      - name: Create Name
        run: echo "SUFFIX=pre.${GITHUB_RUN_ID}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack -c Release --no-build --no-dependencies --version-suffix $SUFFIX
      - name: Push
        run: dotnet nuget push R4Utils/bin/Release/R4Utils.1.0.0-$SUFFIX.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
